[workspace]
members = [
    "loop_cli",
    "loop_lib",
    "meta_cli",
    "meta_git",
    "meta_git_cli",
    "meta_git_lib",
    "meta_rust_cli",
    "meta_project_cli",
    "meta_plugin_api",
]
resolver = "2"
